Remove potential memory leak and double free in default command-based Robot.cpp
wpilibsuite/EclipsePlugins pull request #104
Opened 2017-04-26 02:17 UTC by czipperz

This uses a similar style to the goat example's Robot.cpp: https://github.com/wpilibsuite/EclipsePlugins/blob/efb85e4fc3eccff991c33060d97be1ea535655d3/edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/PacGoat/src/Robot.h

2017-04-26 02:17 UTC, frcjenkins commented
Can one of the admins verify this patch?

2017-04-26 02:24 UTC, calcmogul commented
Where is defaultAuto defined? I don't see it in the patch.

2017-04-26 02:51 UTC, calcmogul requested changes
Nice catch, and I agree with your assessment. This bug was introduced in commit 6c02566 by the way (that's July 2015).

2017-04-26 02:51 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/command-based/Robot.cpp
> +		if (autonomousCommand) {
Please check against nullptr. It's a pointer, not a bool, and that's what PacGoat does.

2017-04-26 02:51 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/command-based/Robot.cpp
> +		if (autonomousCommand) {
Same here.

2017-04-26 02:51 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/command-based/Robot.cpp
>  		// chooser.AddObject("My Auto", new MyAutoCommand());
Add an instance variable for this line too, since it would be a memory leak if uncommented.

2017-04-26 03:12 UTC, czipperz commented
I think I accidentally killed the patch when committing.  I'm going to rebase into a new commit FYI.

2017-04-26 04:07 UTC, calcmogul commented
LGTM

2017-04-26 04:35 UTC, czipperz commented
I hope that this work around will eventually be fixed by overloading or changing SendableChooser to allow for a unique_ptr argument.

2017-04-26 04:40 UTC, calcmogul commented
How would the ownership be handled? SendableChooser keeps an internal map of T&'s and doesn't take ownership of anything at the moment. Adding support for this would require extra bookkeeping inside SendableChooser.

2017-04-26 04:44 UTC, calcmogul commented
Does using std::unique_ptr as class template instantiation not work at the moment?

2017-04-26 05:31 UTC, czipperz commented
I assume that SendableChooser<shared_ptr<int> > works as intended because it compiled when I first saw this bug and was looking for fixes.

The reason unique_ptr doesn't work is because it doesn't provide a means to copy it and getSelected() copies it.

2017-04-26 05:37 UTC, czipperz commented
The keys are already owned: `llvm::StringMap<T> m_choices`

What needs to happen is `T GetSelected()` needs to be changed to `decltype(**(T*)0)* GetSelected()` so for `T = int*`, that returns `int*`. For `T = unique_ptr<int>` it returns `int*`

2017-04-26 05:40 UTC, calcmogul commented
That doesn't work if `T = int` or `T = std::string`.

2017-04-26 05:45 UTC, czipperz commented
AFAIK it does bad stuff by calling `std::string(nullptr)` if you currently
use `std::string`. I've read on Chief Delphi that on doesn't currently work
either.

Chris Gregory

On Apr 25, 2017 10:40 PM, "Tyler Veness" <notifications@github.com> wrote:

> That doesn't work if T = int or T = std::string.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wpilibsuite/EclipsePlugins/pull/104#issuecomment-297243522>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJlqx7X1WOaUmyvSRriasKPAtr_zwkflks5rztjogaJpZM4NIR2O>
> .
>

2017-04-26 08:58 UTC, calcmogul commented
I put together a fix for non-pointer T's and T = std::unique_ptr<U>. See allwpilib#512.

2017-05-10 20:14 UTC, czipperz commented
@calcmogul Are the requested changes done?  GitHub doesn't think they are, but I did change what you commented above.

2017-05-13 04:36 UTC, calcmogul approved these changes

2017-05-16 06:13 UTC, PeterJohnson commented
@frcjenkins retest this please

2017-05-16 06:20 UTC, czipperz commented
@PeterJohnson http://download.eclipse.org/releases/neon/201705151400/content.xml.xz 404s, failing the build.

2017-05-21 00:46 UTC, czipperz commented
It's back up. Please tell Jenkins to retest.

2017-05-21 01:03 UTC, AustinShalit commented
@frcjenkins retest this please

2017-05-25 17:29 UTC, 333fred commented
@frcjenkins retest this please

2017-07-02 04:04 UTC, merged