Changes to enable 3rd party developer libraries.
wpilibsuite/EclipsePlugins pull request #20
Opened 2016-10-13 04:53 UTC by Kevin-OConnor

2016-10-13 06:14 UTC, 333fred requested changes

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.core/src/main/java/edu/wpi/first/wpilib/plugins/core/WPILibCore.java
> +		File directory = new File(WPILibCore.getDefault().getWPILibBaseDir() + "/user");
We shouldn't be using hardcoded path separator strings. Use https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.lang.String-java.lang.String...- to combine path elements.

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.cpp/src/main/java/edu/wpi/first/wpilib/plugins/cpp/WPILibCPPPlugin.java
> +	// TODO: When the 2017 rpath changes, something like this is needed to update 2016 projects
We should file an issue for this so we can track it

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.cpp/src/main/java/edu/wpi/first/wpilib/plugins/cpp/WPILibCPPPlugin.java
> +						File dir = new File(WPILibCore.getDefault().getWPILibBaseDir() + File.separator + "user" + File.separator + "cpp" + File.separator + "lib");
We should also use the `Paths.get` API here, much cleaner.

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.cpp/src/main/java/edu/wpi/first/wpilib/plugins/cpp/WPILibCPPPlugin.java
> +				/*
Dead code?

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.cpp/src/main/resources/cpp-zip/ant/build.properties
> +libDeploy.dir=/usr/local/frc/lib
Do we need to have an LD_LIBRARY_PATH for this?

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.java/src/main/java/edu/wpi/first/wpilib/plugins/java/WPILibJavaPlugin.java
> +		//TODO: This races with the install on first launch (the reason for NullPointerException catch in the first try below)
We should file an issue. Do we have any idea why?

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.java/src/main/java/edu/wpi/first/wpilib/plugins/java/WPILibJavaPlugin.java
> +		//TODO: This races with the install on first launch (the reason for NullPointerException catch in the first try below)
And is there a way to workaround (ie retry)?

2016-10-13 06:14 UTC, 333fred commented on edu.wpi.first.wpilib.plugins.java/src/main/resources/java-zip/ant/build.properties
> +libDeploy.dir=/usr/local/frc/lib
We'll probably need to add this to the runtime classpath, right?

2016-10-13 11:23 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.cpp/src/main/resources/cpp-zip/ant/build.properties
> +libDeploy.dir=/usr/local/frc/lib
No, it's already on the library path, it's where a bunch of the other .so's we link against are located.

2016-10-13 11:24 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.core/src/main/java/edu/wpi/first/wpilib/plugins/core/WPILibCore.java
> +		File directory = new File(WPILibCore.getDefault().getWPILibBaseDir() + "/user");
Yep, I'll fix that one

2016-10-13 11:29 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.cpp/src/main/java/edu/wpi/first/wpilib/plugins/cpp/WPILibCPPPlugin.java
> +	// TODO: When the 2017 rpath changes, something like this is needed to update 2016 projects
Done.

2016-10-13 11:30 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.cpp/src/main/java/edu/wpi/first/wpilib/plugins/cpp/WPILibCPPPlugin.java
> +				/*
It's the code to set linker flags per the rpath TODO at the top. I'll add a comment to indicate that

2016-10-13 11:36 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.java/src/main/resources/java-zip/ant/build.properties
> +libDeploy.dir=/usr/local/frc/lib
It is used for .so's which someone has chosen not to already wrap up in their JAR and load like WPILib loads the JNI one. 3rd party JARs are bundled with the user program JAR right now. I have not checked to verify that it is on java.library.path (where Java looks for libraries on a System.loadLibrary() call) but I believe it should be.

2016-10-13 11:40 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.java/src/main/java/edu/wpi/first/wpilib/plugins/java/WPILibJavaPlugin.java
> +		//TODO: This races with the install on first launch (the reason for NullPointerException catch in the first try below)
Issue filed. For now I think we should leave this as is as the impact is fairly low for Beta 1 (it's only an issue on your first plugin install on a given machine, otherwise the properties exist) as teams likely won't be installing fresh (Neon not yet supported).

2016-10-14 01:49 UTC, 333fred approved these changes

2016-10-14 01:50 UTC, merged