Fall back to .lan address if .local doesn't work
wpilibsuite/EclipsePlugins pull request #68
Opened 2016-12-15 06:41 UTC by sciencewhiz

Fixes #63

2016-12-15 06:41 UTC, frcjenkins commented
Can one of the admins verify this patch?

2016-12-15 08:44 UTC, PeterJohnson commented
@frcjenkins test this please

2016-12-15 16:47 UTC, Kevin-OConnor requested changes
Minor nits, but there is enough confusion with teams about how this all works that I would prefer to be accurate with it.

2016-12-15 16:47 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.cpp/src/main/resources/cpp-zip/ant/build.xml
> +			<echo>roboRIO found via mDNS .lan</echo>
The .lan lookup is DNS.

2016-12-15 16:47 UTC, Kevin-OConnor commented on edu.wpi.first.wpilib.plugins.java/src/main/resources/java-zip/ant/build.xml
> +			<echo>roboRIO found via mDNS .lan</echo>
Same as above

2016-12-16 07:10 UTC, 333fred commented
@frcjenkins ok to test

2016-12-16 18:40 UTC, Kevin-OConnor approved these changes

2016-12-16 18:51 UTC, merged