[WIP] Remove can talon
wpilibsuite/EclipsePlugins pull request #78
Opened 2016-12-30 00:27 UTC by AustinShalit

closes #75 

Still need to do the C++ version of UltrasonicPID.

2016-12-30 06:29 UTC, calcmogul requested changes

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
> +#include <IterativeRobot.h>
The WPILib headers should be in lexographic order. `#include <cmath>` should go before them rather than `#include <math.h>` going after.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
> +	void robotInit() {
In C++, these are capitalized. I recommend adding the override keyword after the parentheses to catch this mistake at compile time.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
> +	static constexpr double ANGLE_SETPOINT = 0.0;
The style guide requires `kAngleSetpoint`, not `ANGLE_SETPOINT` in both languages.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/GyroMecanum/src/Robot.cpp
> +#include <IterativeRobot.h>
Include order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/GyroMecanum/src/Robot.cpp
> +	RobotDrive myRobot { 0, 1, 2, 3 };
Spaces shouldn't be used as padding here. They behave like parentheses here and should be formatted as such.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/GyroMecanum/src/Robot.cpp
> +class Robot: public IterativeRobot {
A space should go between `Robot` and `:`.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
> +	static constexpr double KP = 0.005;  // Propotional turning constant
Comment typo and name should be `kP` according to the style guide. An alternative used in control theory often is `Kp`.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
> +	static constexpr double VOLTS_PER_DEGREE_PER_SECOND = 0.0128;
Naming.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
> +class Robot: public IterativeRobot {
Space between `Robot` and `:`.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/GyroMecanum/src/Robot.cpp
> +	void robotInit() {
Incorrect capitalization and should add override keyword.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Ultrasonic/src/Robot.cpp
> +#include <IterativeRobot.h>
Include order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Ultrasonic/src/Robot.cpp
> +	static constexpr int HOLD_DISTANCE = 12;
Constant name.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/UltrasonicPID/src/Robot.cpp
> +#include <RobotDrive.h>
Include order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/UltrasonicPID/src/Robot.cpp
> +class Robot: public IterativeRobot {
Space between `Robot` and `:`.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/Gyro/src/org/usfirst/frc/team190/robot/Robot.java
> +import edu.wpi.first.wpilibj.IterativeRobot;
Import order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/Gyro/src/org/usfirst/frc/team190/robot/Robot.java
> +    private static final double ANGLE_SETPOINT = 0.0;
Incorrect constant naming.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/GyroMecanum/src/org/usfirst/frc/team190/robot/Robot.java
>  import edu.wpi.first.wpilibj.RobotDrive;
Import order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/Ultrasonic/src/org/usfirst/frc/team190/robot/Robot.java
>  import edu.wpi.first.wpilibj.AnalogInput;
Import order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/Ultrasonic/src/org/usfirst/frc/team190/robot/Robot.java
> +	private static final double HOLD_DISTANCE = 12.0;
Constant naming.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/UltrasonicPID/src/org/usfirst/frc/team190/robot/Robot.java
> +import edu.wpi.first.wpilibj.AnalogInput;
Import order.

2016-12-30 06:29 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/UltrasonicPID/src/org/usfirst/frc/team190/robot/Robot.java
> +	private static final double HOLD_DISTANCE = 12.0;
Constant naming.

2016-12-31 07:27 UTC, calcmogul requested changes

2016-12-31 07:27 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/Gyro/src/Robot.cpp
>  #include <AnalogGyro.h>
The include order here should be:

> #include \<cmath\>
>
> #include <AnalogGyro.h>
> #include <IterativeRobot.h>
> #include <Joystick.h>
> #include <RobotDrive.h>

2016-12-31 07:27 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/UltrasonicPID/src/Robot.cpp
> +	static constexpr double VALUE_TO_INCHES = 0.125;
`VALUE_TO_INCHES` should be `kValueToInches`.

2016-12-31 07:27 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/UltrasonicPID/src/Robot.cpp
> +	static constexpr int HOLD_DISTANCE = 12;
`HOLD_DISTANCE` should be `kHoldDistance`.

2016-12-31 07:27 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/Gyro/src/org/usfirst/frc/team190/robot/Robot.java
> +    private static final double kVoltsPerDegreePerSecond = .0128;
The value should be prefixed with 0 to match the other constants in the examples.

2016-12-31 07:27 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.java/resources/templates/examples/GyroMecanum/src/org/usfirst/frc/team190/robot/Robot.java
> +    private static final double kVoltsPerDegreePerSecond = .0128;
Add a 0 prefix.

2016-12-31 07:27 UTC, calcmogul commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/UltrasonicPID/src/Robot.cpp
> +	AnalogInput ultrasonic{0};
The formatter would add padding here.

2016-12-31 23:42 UTC, sciencewhiz commented
In examples.xml, the CAN tag needs to be removed from the examples where CAN Talon was replaced.

2017-01-01 02:43 UTC, calcmogul approved these changes

2017-01-01 03:00 UTC, PeterJohnson commented
Some of the formatting here looks a little wonky.  Or is this Eclipse style formatting instead of wpilib?

2017-01-01 03:58 UTC, sciencewhiz commented
I'm not sure I like going away from named constants for ports.

2017-01-02 02:02 UTC, sciencewhiz approved these changes
Only comment is it would be nice if the Ultrasonic and gyro examples listed what sensors they were designed for. For ultrasonic, I assume it's a Maxbotix of some sort, and for gyro it's probably an Analog Devices analog gyro of some type.

2017-01-02 03:27 UTC, merged