Fix grammar in a few example descriptions
wpilibsuite/EclipsePlugins pull request #81
Opened 2016-12-31 23:40 UTC by sciencewhiz

2016-12-31 23:44 UTC, PeterJohnson requested changes

2016-12-31 23:44 UTC, PeterJohnson commented on edu.wpi.first.wpilib.plugins.cpp/resources/templates/examples/examples.xml
> +        <description>An example program which demonsrate the use of Mecanum Drive with the RobotDrive class</description>
Typo in this line.

2017-01-01 00:13 UTC, AustinShalit approved these changes

2017-01-01 02:58 UTC, PeterJohnson approved these changes

2017-01-01 02:58 UTC, merged